# VariablesIO/save_suspension.py

def save_susp():
    from suspension.io.variables import S
    if S.file_mame == '':
        from tkinter import filedialog
        from pathlib import Path
        S.file_mame = str(filedialog.asksaveasfile(initialdir = Path.cwd(),defaultextension=".txt",filetypes=(("text files","*.txt"),("all files","*.*"))))
        S.file_mame = S.file_mame.replace("<_io.TextIOWrapper name='","")
        S.file_mame = S.file_mame.replace("' mode='w' encoding='cp1252'>","")
    if S.file_mame == 'None':
        S.file_mame = ''
    else:
        with open(S.file_mame, 'w') as f:
            f.write(save_susp_string())

def save_as_susp():
    from suspension.io.variables import S
    from tkinter import filedialog
    from pathlib import Path
    S.file_mame = str(filedialog.asksaveasfile(initialdir = Path.cwd(),defaultextension=".txt",filetypes=(("text files","*.txt"),("all files","*.*"))))
    S.file_mame = S.file_mame.replace("<_io.TextIOWrapper name='","")
    S.file_mame = S.file_mame.replace("' mode='w' encoding='cp1252'>","")
    save_susp() 

def save_susp_string():
    import numpy as np
    from suspension.io.variables import constant,S,x,y,z
    from suspension.io.initialize_IO import inputs
    line = 'units,{}'.format(S.units)
    output = line
    line = '\nreversed front x,{}'.format(S.reversed_front_x)
    output += line
    line = '\ntire loading,{}'.format(S.simulate_tire_loading)
    output += line
    line = '\nsample points,{}'.format(S.sample_points)
    output += line
    susp_type = 'SA triangualted 4 link'
    if inputs.F.panhard:
        if inputs.F.U_count == 1:
            susp_type = 'SA 3 link with panhard'
        else:
            if inputs.F.LF[x] == inputs.F.UF[x] or inputs.F.LF[y] == inputs.F.UF[y] or inputs.F.LF[z] == inputs.F.UF[z]:
                susp_type = 'SA 4 link with panhard'
            else:
                susp_type = 'SA radius arm'
    line = '\nfront type,{}'.format(susp_type)
    output += line
    line = '\nfront upper frame,{},{},{}'.format(inputs.F.UF[x],inputs.F.UF[y],inputs.F.UF[z])
    output += line
    line = '\nfront upper axle,{},{},{}'.format(inputs.F.UA[x],inputs.F.UA[y],inputs.F.UA[z])
    output += line
    line = '\nfront lower frame,{},{},{}'.format(inputs.F.LF[x],inputs.F.LF[y],inputs.F.LF[z])
    output += line
    line = '\nfront lower axle,{},{},{}'.format(inputs.F.LA[x],inputs.F.LA[y],inputs.F.LA[z])
    output += line
    line = '\nfront panhard frame,{},{},{}'.format(inputs.F.PF[x],inputs.F.PF[y],inputs.F.PF[z])
    output += line
    line = '\nfront panhard axle,{},{},{}'.format(inputs.F.PA[x],inputs.F.PA[y],inputs.F.PA[z])
    output += line
    line = '\nfront bump,{}'.format(inputs.F.bump)
    output += line
    line = '\nfront droop,{}'.format(inputs.F.droop)
    output += line
    line = '\nfront tire radius,{}'.format(inputs.F.tire_radius)
    output += line
    line = '\nfront tire diameter,{}'.format(inputs.F.tire_diameter)
    output += line
    line = '\nfront tire width,{}'.format(inputs.F.tire_width)
    output += line
    line = '\nfront portal height,{}'.format(inputs.F.portal_height)
    output += line
    line = '\nfront track width,{}'.format(inputs.F.track_width)
    output += line
    line = '\nfront mass,{}'.format(inputs.F.unsprung_mass)
    output += line
    line = '\nfront upper od,{}'.format(inputs.F.U_OD)
    output += line
    line = '\nfront lower od,{}'.format(inputs.F.L_OD)
    output += line
    line = '\nfront panhard od,{}'.format(inputs.F.P_OD)
    output += line
    line = '\nfront upper wall,{}'.format(inputs.F.U_wall)
    output += line
    line = '\nfront lower wall,{}'.format(inputs.F.L_wall)
    output += line
    line = '\nfront panhard wall,{}'.format(inputs.F.P_wall)
    output += line
    line = '\nfront upper solid,{}'.format(inputs.F.U_solid)
    output += line
    line = '\nfront lower solid,{}'.format(inputs.F.L_solid)
    output += line
    line = '\nfront panhard solid,{}'.format(inputs.F.P_solid)
    output += line
    name = inputs.F.U_material
    mat_index = constant.materials.name.index(name)
    yield_strength = constant.materials.yield_strength[mat_index]
    modulus_elasticity = constant.materials.modulus_elasticity[mat_index]
    density = constant.materials.density[mat_index]
    note = constant.materials.notes[mat_index]
    line = '\nfront upper material,{},{},{},{},{}'.format(name,yield_strength,modulus_elasticity,density,note) # pass all material data
    output += line
    name = inputs.F.L_material
    mat_index = constant.materials.name.index(name)
    yield_strength = constant.materials.yield_strength[mat_index]
    modulus_elasticity = constant.materials.modulus_elasticity[mat_index]
    density = constant.materials.density[mat_index]
    note = constant.materials.notes[mat_index]
    line = '\nfront lower material,{},{},{},{},{}'.format(name,yield_strength,modulus_elasticity,density,note) # pass all material data
    output += line
    name = inputs.F.P_material
    mat_index = constant.materials.name.index(name)
    yield_strength = constant.materials.yield_strength[mat_index]
    modulus_elasticity = constant.materials.modulus_elasticity[mat_index]
    density = constant.materials.density[mat_index]
    note = constant.materials.notes[mat_index]
    line = '\nfront panhard material,{},{},{},{},{}'.format(name,yield_strength,modulus_elasticity,density,note) # pass all material data
    output += line
    name = inputs.F.U_rod_end
    RE_index = constant.rod_ends.name.index(name)
    radial_load = constant.rod_ends.radial_load[RE_index] 
    weight = constant.rod_ends.weight[RE_index] 
    hole_diameter = constant.rod_ends.hole_diameter[RE_index]
    thread_diameter = constant.rod_ends.shank_diameter[RE_index] 
    thread_pitch = constant.rod_ends.thread[RE_index]
    line = '\nfront upper rod end,{},{},{},{},{},{}'.format(name,radial_load,weight,hole_diameter,thread_diameter,thread_pitch) # pass all rod end data
    output += line
    name = inputs.F.L_rod_end
    RE_index = constant.rod_ends.name.index(name)
    radial_load = constant.rod_ends.radial_load[RE_index] 
    weight = constant.rod_ends.weight[RE_index] 
    hole_diameter = constant.rod_ends.hole_diameter[RE_index]
    thread_diameter = constant.rod_ends.shank_diameter[RE_index] 
    thread_pitch = constant.rod_ends.thread[RE_index]
    line = '\nfront lower rod end,{},{},{},{},{},{}'.format(name,radial_load,weight,hole_diameter,thread_diameter,thread_pitch) # pass all rod end data
    output += line
    name = inputs.F.P_rod_end
    RE_index = constant.rod_ends.name.index(name)
    radial_load = constant.rod_ends.radial_load[RE_index] 
    weight = constant.rod_ends.weight[RE_index] 
    hole_diameter = constant.rod_ends.hole_diameter[RE_index]
    thread_diameter = constant.rod_ends.shank_diameter[RE_index] 
    thread_pitch = constant.rod_ends.thread[RE_index]
    line = '\nfront panhard rod end,{},{},{},{},{},{}'.format(name,radial_load,weight,hole_diameter,thread_diameter,thread_pitch) # pass all rod end data
    output += line
    line = '\nfront pinion,{},{},{}'.format(inputs.F.pinion[x],inputs.F.pinion[y],inputs.F.pinion[z])
    output += line
    line = '\nfront T case,{},{},{}'.format(inputs.F.T_case[x],inputs.F.T_case[y],inputs.F.T_case[z])
    output += line
    line = '\nfront pinion location method,{}'.format(inputs.F.pinion_location_method)
    output += line
    line = '\nfront T case side angle,{}'.format(inputs.F.T_case_side_angle)
    output += line
    line = '\nfront T case top angle,{}'.format(inputs.F.T_case_top_angle)
    output += line
    line = '\nfront pinion angle,{}'.format(inputs.F.pinion_angle)
    output += line
    line = '\nfront pinion hypoid,{}'.format(inputs.F.pinion_hypoid)
    output += line
    line = '\nfront pinion length,{}'.format(inputs.F.pinion_length)
    output += line
    line = '\nfront caster,{}'.format(inputs.F.caster)
    output += line
    line = '\nfront spring method,{}'.format(inputs.F.spring_method)
    output += line
    line = '\nfront freq goal,{}'.format(inputs.F.freq_goal)
    output += line
    line = '\nfront preload goal,{}'.format(inputs.F.preload_goal)
    output += line
    line = '\nfront step up ratio,{}'.format(inputs.F.step_up_ratio)
    output += line
    line = '\nfront used main spring,{}'.format(inputs.F.used_main_spring)
    output += line
    line = '\nfront used tender spring,{}'.format(inputs.F.used_tender_spring)
    output += line
    line = '\nfront shock 1 size,{}'.format(inputs.F.shock1.size)
    output += line
    line = '\nfront shock 1 travel,{}'.format(inputs.F.shock1.travel)
    output += line
    line = '\nfront shock 1 main spring extra length,{}'.format(inputs.F.shock1.main_spring_extra_length)
    output += line
    line = '\nfront shock 1 chassis mount,{},{},{}'.format(inputs.F.shock1.chassis_mount[x],inputs.F.shock1.chassis_mount[y],inputs.F.shock1.chassis_mount[z])
    output += line
    line = '\nfront shock 1 susp mount,{},{},{}'.format(inputs.F.shock1.susp_mount[x],inputs.F.shock1.susp_mount[y],inputs.F.shock1.susp_mount[z])
    output += line
    line = '\nfront shock 1 location,{}'.format(inputs.F.shock1.location)
    output += line
    line = '\nfront shock 1 length extended,{}'.format(inputs.F.shock1.length_extended)
    output += line
    line = '\nfront shock 1 length compressed,{}'.format(inputs.F.shock1.length_compressed)
    output += line
    line = '\nfront shock 2 size,{}'.format(inputs.F.shock2.size)
    output += line
    line = '\nfront shock 2 travel,{}'.format(inputs.F.shock2.travel)
    output += line
    line = '\nfront shock 2 chassis mount,{},{},{}'.format(inputs.F.shock2.chassis_mount[x],inputs.F.shock2.chassis_mount[y],inputs.F.shock2.chassis_mount[z])
    output += line
    line = '\nfront shock 2 susp mount,{},{},{}'.format(inputs.F.shock2.susp_mount[x],inputs.F.shock2.susp_mount[y],inputs.F.shock2.susp_mount[z])
    output += line
    line = '\nfront shock 2 location,{}'.format(inputs.F.shock2.location)
    output += line
    line = '\nfront shock 2 exists,{}'.format(inputs.F.shock2.exists)
    output += line
    line = '\nfront shock 2 length extended,{}'.format(inputs.F.shock2.length_extended)
    output += line
    line = '\nfront shock 2 length compressed,{}'.format(inputs.F.shock2.length_compressed)
    output += line
    line = '\nfront pitch travel,{}'.format(inputs.F.pitch_travel)
    output += line
    susp_type = 'SA triangualted 4 link'
    if inputs.R.panhard:
        if inputs.R.U_count == 1:
            susp_type = 'SA 3 link with panhard'
        else:
            if inputs.R.LF[x] == inputs.R.UF[x] or inputs.R.LF[y] == inputs.R.UF[y] or inputs.R.LF[z] == inputs.R.UF[z]:
                susp_type = 'SA 4 link with panhard'
            else:
                susp_type = 'SA radius arm'
    line = '\nrear type,{}'.format(susp_type)
    output += line
    line = '\nrear upper frame,{},{},{}'.format(inputs.R.UF[x],inputs.R.UF[y],inputs.R.UF[z])
    output += line
    line = '\nrear upper axle,{},{},{}'.format(inputs.R.UA[x],inputs.R.UA[y],inputs.R.UA[z])
    output += line
    line = '\nrear lower frame,{},{},{}'.format(inputs.R.LF[x],inputs.R.LF[y],inputs.R.LF[z])
    output += line
    line = '\nrear lower axle,{},{},{}'.format(inputs.R.LA[x],inputs.R.LA[y],inputs.R.LA[z])
    output += line
    line = '\nrear panhard frame,{},{},{}'.format(inputs.R.PF[x],inputs.R.PF[y],inputs.R.PF[z])
    output += line
    line = '\nrear panhard axle,{},{},{}'.format(inputs.R.PA[x],inputs.R.PA[y],inputs.R.PA[z])
    output += line
    line = '\nrear bump,{}'.format(inputs.R.bump)
    output += line
    line = '\nrear droop,{}'.format(inputs.R.droop)
    output += line
    line = '\nrear tire radius,{}'.format(inputs.R.tire_radius)
    output += line
    line = '\nrear tire diameter,{}'.format(inputs.R.tire_diameter)
    output += line
    line = '\nrear tire width,{}'.format(inputs.R.tire_width)
    output += line
    line = '\nrear portal height,{}'.format(inputs.R.portal_height)
    output += line
    line = '\nrear track width,{}'.format(inputs.R.track_width)
    output += line
    line = '\nrear mass,{}'.format(inputs.R.unsprung_mass)
    output += line
    line = '\nrear upper od,{}'.format(inputs.R.U_OD)
    output += line
    line = '\nrear lower od,{}'.format(inputs.R.L_OD)
    output += line
    line = '\nrear panhard od,{}'.format(inputs.R.P_OD)
    output += line
    line = '\nrear upper wall,{}'.format(inputs.R.U_wall)
    output += line
    line = '\nrear lower wall,{}'.format(inputs.R.L_wall)
    output += line
    line = '\nrear panhard wall,{}'.format(inputs.R.P_wall)
    output += line
    line = '\nrear upper solid,{}'.format(inputs.R.U_solid)
    output += line
    line = '\nrear lower solid,{}'.format(inputs.R.L_solid)
    output += line
    line = '\nrear panhard solid,{}'.format(inputs.R.P_solid)
    output += line
    name = inputs.R.U_material
    mat_index = constant.materials.name.index(name)
    yield_strength = constant.materials.yield_strength[mat_index]
    modulus_elasticity = constant.materials.modulus_elasticity[mat_index]
    density = constant.materials.density[mat_index]
    note = constant.materials.notes[mat_index]
    line = '\nrear upper material,{},{},{},{},{}'.format(name,yield_strength,modulus_elasticity,density,note) # pass all material data
    output += line
    name = inputs.R.L_material
    mat_index = constant.materials.name.index(name)
    yield_strength = constant.materials.yield_strength[mat_index]
    modulus_elasticity = constant.materials.modulus_elasticity[mat_index]
    density = constant.materials.density[mat_index]
    note = constant.materials.notes[mat_index]
    line = '\nrear lower material,{},{},{},{},{}'.format(name,yield_strength,modulus_elasticity,density,note) # pass all material data
    output += line
    name = inputs.R.P_material
    mat_index = constant.materials.name.index(name)
    yield_strength = constant.materials.yield_strength[mat_index]
    modulus_elasticity = constant.materials.modulus_elasticity[mat_index]
    density = constant.materials.density[mat_index]
    note = constant.materials.notes[mat_index]
    line = '\nrear panhard material,{},{},{},{},{}'.format(name,yield_strength,modulus_elasticity,density,note) # pass all material data
    output += line
    name = inputs.R.U_rod_end
    RE_index = constant.rod_ends.name.index(name)
    radial_load = constant.rod_ends.radial_load[RE_index] 
    weight = constant.rod_ends.weight[RE_index] 
    hole_diameter = constant.rod_ends.hole_diameter[RE_index]
    thread_diameter = constant.rod_ends.shank_diameter[RE_index] 
    thread_pitch = constant.rod_ends.thread[RE_index]
    line = '\nrear upper rod end,{},{},{},{},{},{}'.format(name,radial_load,weight,hole_diameter,thread_diameter,thread_pitch) # pass all rod end data
    output += line
    name = inputs.R.L_rod_end
    RE_index = constant.rod_ends.name.index(name)
    radial_load = constant.rod_ends.radial_load[RE_index] 
    weight = constant.rod_ends.weight[RE_index] 
    hole_diameter = constant.rod_ends.hole_diameter[RE_index]
    thread_diameter = constant.rod_ends.shank_diameter[RE_index] 
    thread_pitch = constant.rod_ends.thread[RE_index]
    line = '\nrear lower rod end,{},{},{},{},{},{}'.format(name,radial_load,weight,hole_diameter,thread_diameter,thread_pitch) # pass all rod end data
    output += line
    name = inputs.R.P_rod_end
    RE_index = constant.rod_ends.name.index(name)
    radial_load = constant.rod_ends.radial_load[RE_index] 
    weight = constant.rod_ends.weight[RE_index] 
    hole_diameter = constant.rod_ends.hole_diameter[RE_index]
    thread_diameter = constant.rod_ends.shank_diameter[RE_index] 
    thread_pitch = constant.rod_ends.thread[RE_index]
    line = '\nrear panhard rod end,{},{},{},{},{},{}'.format(name,radial_load,weight,hole_diameter,thread_diameter,thread_pitch) # pass all rod end data
    output += line
    line = '\nrear pinion,{},{},{}'.format(inputs.R.pinion[x],inputs.R.pinion[y],inputs.R.pinion[z])
    output += line
    line = '\nrear T case,{},{},{}'.format(inputs.R.T_case[x],inputs.R.T_case[y],inputs.R.T_case[z])
    output += line
    line = '\nrear pinion location method,{}'.format(inputs.R.pinion_location_method)
    output += line
    line = '\nrear T case side angle,{}'.format(inputs.R.T_case_side_angle)
    output += line
    line = '\nrear T case top angle,{}'.format(inputs.R.T_case_top_angle)
    output += line
    line = '\nrear pinion angle,{}'.format(inputs.R.pinion_angle)
    output += line
    line = '\nrear pinion hypoid,{}'.format(inputs.R.pinion_hypoid)
    output += line
    line = '\nrear pinion length,{}'.format(inputs.R.pinion_length)
    output += line
    line = '\nrear caster,{}'.format(inputs.R.caster)
    output += line
    line = '\nrear spring method,{}'.format(inputs.R.spring_method)
    output += line
    line = '\nrear freq goal,{}'.format(inputs.R.freq_goal)
    output += line
    line = '\nrear preload goal,{}'.format(inputs.R.preload_goal)
    output += line
    line = '\nrear step up ratio,{}'.format(inputs.R.step_up_ratio)
    output += line
    line = '\nrear used main spring,{}'.format(inputs.R.used_main_spring)
    output += line
    line = '\nrear used tender spring,{}'.format(inputs.R.used_tender_spring)
    output += line
    line = '\nrear shock 1 size,{}'.format(inputs.R.shock1.size)
    output += line
    line = '\nrear shock 1 travel,{}'.format(inputs.R.shock1.travel)
    output += line
    line = '\nrear shock 1 main spring extra length,{}'.format(inputs.R.shock1.main_spring_extra_length)
    output += line
    line = '\nrear shock 1 chassis mount,{},{},{}'.format(inputs.R.shock1.chassis_mount[x],inputs.R.shock1.chassis_mount[y],inputs.R.shock1.chassis_mount[z])
    output += line
    line = '\nrear shock 1 susp mount,{},{},{}'.format(inputs.R.shock1.susp_mount[x],inputs.R.shock1.susp_mount[y],inputs.R.shock1.susp_mount[z])
    output += line
    line = '\nrear shock 1 location,{}'.format(inputs.R.shock1.location)
    output += line
    line = '\nrear shock 1 length extended,{}'.format(inputs.R.shock1.length_extended)
    output += line
    line = '\nrear shock 1 length compressed,{}'.format(inputs.R.shock1.length_compressed)
    output += line
    line = '\nrear shock 2 size,{}'.format(inputs.R.shock2.size)
    output += line
    line = '\nrear shock 2 travel,{}'.format(inputs.R.shock2.travel)
    output += line
    line = '\nrear shock 2 chassis mount,{},{},{}'.format(inputs.R.shock2.chassis_mount[x],inputs.R.shock2.chassis_mount[y],inputs.R.shock2.chassis_mount[z])
    output += line
    line = '\nrear shock 2 susp mount,{},{},{}'.format(inputs.R.shock2.susp_mount[x],inputs.R.shock2.susp_mount[y],inputs.R.shock2.susp_mount[z])
    output += line
    line = '\nrear shock 2 location,{}'.format(inputs.R.shock2.location)
    output += line
    line = '\nrear shock 2 exists,{}'.format(inputs.R.shock2.exists)
    output += line
    line = '\nrear shock 2 length extended,{}'.format(inputs.R.shock2.length_extended)
    output += line
    line = '\nrear shock 2 length compressed,{}'.format(inputs.R.shock2.length_compressed)
    output += line
    line = '\nrear pitch travel,{}'.format(inputs.R.pitch_travel)
    output += line
    line = '\nvehicle wheelbase,{}'.format(inputs.V.wheelbase)
    output += line
    line = '\nvehicle drive bias,{}'.format(inputs.V.drive_bias)
    output += line
    line = '\nvehicle brake bias,{}'.format(inputs.V.brake_bias)
    output += line
    line = '\nvehicle CG height,{}'.format(inputs.V.CG_height)
    output += line
    line = '\nvehicle weight distribution,{}'.format(inputs.V.weight_distribution)
    output += line
    line = '\nvehicle mass,{}'.format(inputs.V.mass)
    output += line
    line = '\nvehicle acceleration,{}'.format(inputs.V.acceleration)
    output += line
    line = '\nvehicle transverse acceleration,{}'.format(inputs.V.transverse_acceleration)
    output += line
    line = '\nvehicle desired FS yield,{}'.format(inputs.V.Desired_FS_Yield)
    output += line
    line = '\nvehicle desired FS buckling,{}'.format(inputs.V.Desired_FS_Buckling)
    output += line
    line = '\nvehicle desired FS bending,{}'.format(inputs.V.Desired_FS_Bending)
    output += line
    line = '\nvehicle desired FS rod end,{}'.format(inputs.V.Desired_FS_RE)
    output += line
    line = '\nvehicle desired FS denting,{}'.format(inputs.V.Desired_FS_Dent)
    output += line
    line = '\nvehicle desired speed,{}'.format(inputs.V.desired_speed)
    output += line
    line = '\nvehicle freq approach,{}'.format(inputs.V.freq_approach)
    output += line
    line = '\nvehicle spring method,{}'.format(inputs.V.spring_method)
    output += line
    line = '\nvehicle pitch slope,{}'.format(inputs.V.pitch_slope)
    output += line
    line = '\nvehicle pitch acceleration,{}'.format(inputs.V.pitch_acceleration)
    output += line
    line = '\nvehicle pitch drive bias,{}'.format(inputs.V.pitch_drive_bias)
    output += line
    line = '\nvehicle pitch brake bias,{}'.format(inputs.V.pitch_brake_bias)
    output += line
    return output